# 1. Use an official Node.js runtime as a parent image
FROM node:18-alpine

# 2. Set the working directory inside the container
WORKDIR /app

# 3. Copy package.json and install dependencies
COPY package.json ./
RUN npm install

# 4. Copy the rest of your app code
COPY . .

# 5. We don't specify CMD here because we have two different scripts (server vs worker)
# We will specify the command in docker-compose.yml